# Generated by Django 3.2.13 on 2022-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('PAID', 'PAID'), ('FAIL', 'FAIL'), ('DONE', 'DONE')], default='CREATE', max_length=20),
        ),
    ]
