# Generated by Django 3.2.13 on 2022-06-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-created_at']},
        ),
    ]
