# Generated by Django 3.2.13 on 2022-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0018_alter_product_image'),
        ('orders', '0005_auto_20220618_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='terminals.product'),
        ),
    ]
