# Generated by Django 3.2.13 on 2022-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
