# Generated by Django 3.2.13 on 2022-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
