version: "3.0"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    environment:
      MYSQL_DATABASE: kiot_management
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - djangonetwork

  redis:
    image: redis:6.2.3
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - djangonetwork

volumes:
  postgres-data:
    external: false

networks:
  djangonetwork:
    driver: bridge
