# Generated by Django 3.2.13 on 2022-06-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-created_at']},
        ),
    ]
