# Generated by Django 3.2.13 on 2022-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='code',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
