# Generated by Django 3.2.13 on 2022-06-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_terminal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='type',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('EXTEND', 'EXTEND'), ('PAID', 'PAID'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=20),
        ),
    ]
