# Generated by Django 3.2.13 on 2022-06-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0008_terminal_time_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='type',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('EXTEND', 'EXTEND'), ('PAID', 'PAID'), ('EXPIRED', 'EXPIRED'), ('UNKNOWN', 'UNKNOWN'), ('FAIL', 'FAIL')], default='UNKNOWN', max_length=20),
        ),
    ]
