# Generated by Django 3.2.13 on 2022-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0009_alter_terminal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='extend_max_quantity_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='extend_time_selling',
            field=models.IntegerField(default=0),
        ),
    ]
