# Generated by Django 3.2.13 on 2022-06-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0015_alter_catalogimport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='terminalpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='terminal',
            table='-terminals',
        ),
    ]
