# Generated by Django 3.2.13 on 2022-06-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0016_auto_20220618_1704'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='terminal',
            table='terminals',
        ),
    ]
