# Generated by Django 3.2.13 on 2022-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='create_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_id',
            field=models.CharField(default='60559ff1-af5f-48e8-95c6-dbec6ed16621', max_length=50),
            preserve_default=False,
        ),
    ]
