# Generated by Django 3.2.13 on 2022-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220614_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('REGISTER_TERMINAL', 'REGISTER_TERMINAL'), ('EXTEND_TERMINAL', 'EXTEND_TERMINAL'), ('ORDER', 'ORDER')], default='ORDER', max_length=20),
        ),
    ]
